name: Deploy Mario Builder 64 Level JSON Site
on:
  push:
    branches:
      - main
      - feat/deser
      - gh-pages
    paths:
      - "level-json/site/**"
      - "level-json/parser.ts"
      - "level-json/serializer.ts"
      - "level-json/types.ts"
      - "level-json/common.ts"
      - ".github/workflows/deploy.yml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Bundle main.ts
        run: |
          cd level-json/site
          deno bundle main.ts main.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: level-json/site
          publish_branch: gh-pages
