# GitHub Actions workflow for Mario-Builder-64-Serde
# Runs Deno tests and builds the static site for PRs and main branch

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run Deno tests
        run: deno test -A
      - name: Build static site
        run: |
          cd site
          bash build.sh
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload site directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
