# GitHub Actions workflow for Mario-Builder-64-Serde
# Runs Deno tests and builds the static site for PRs and main branch

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run Deno tests
        run: deno test -A
      - name: Build static site
        run: |
          cd site
          bash build.sh
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
